name: mobile_assistant_client
description: AirController desktop app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1
  device_info_plus: ^2.1.0
  desktop_window: ^0.4.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  connectivity_plus: ^2.0.2
  network_info_plus: ^2.0.2
  fluttertoast: ^8.0.8
  syncfusion_flutter_datagrid: ^19.3.48
  syncfusion_flutter_core: ^19.3.48
  http: ^0.13.4
  statusbarmanager: ^0.0.1
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  material_segmented_control: ^3.1.2
  flutter_staggered_grid_view: ^0.4.1
  cached_network_image: ^3.1.0+1
  path_provider: ^2.0.6
  sticky_headers: ^0.2.0
  extended_image: ^6.0.1
  flutter_html: ^2.1.5
  rflutter_alert: ^2.0.4
  visibility_detector: ^0.2.2
  event_bus: ^2.0.0
  flutter_smart_dialog: ^3.0.2
  data_table_2: ^2.2.0
  url_launcher: ^6.0.17
  neat_periodic_task: ^2.0.0
  file_picker: ^4.3.1
  flowder:
    git:
      url: https://github.com/yuanhoujun/flowder
  flutter_markdown: ^0.6.9
  qr_flutter: ^4.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/fonts/
     - assets/docs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Black.otf
        - asset: assets/fonts/NotoSansSC-Bold.otf
        - asset: assets/fonts/NotoSansSC-Light.otf
        - asset: assets/fonts/NotoSansSC-Medium.otf
        - asset: assets/fonts/NotoSansSC-Regular.otf
        - asset: assets/fonts/NotoSansSC-Thin.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
